// Copyright 2026 sbg_driver maintainers
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#include "sbg_driver/driver_node.hpp"

#include <array>
#include <chrono>
#include <format>
#include <rclcpp_components/register_node_macro.hpp>
#include <string>
#include <string_view>
#include <utility>
#include <vector>

// Generated by generate_parameter_library from params/sbg_driver_params.yaml.
// Lives under build/sbg_driver/include/sbg_driver/ at build time.
#include "sbg_driver/sbg_driver_params.hpp"

namespace sbg_driver
{

namespace
{

// ---- configure_device.* param-string → typed sbg:: enum mappers ----
// generate_parameter_library's one_of<> validation guarantees the input is one
// of the listed strings, so the trailing return is just the default branch.

sbg::MotionProfile motion_profile_from_string(std::string_view s)
{
  using enum sbg::MotionProfile;
  constexpr std::array<std::pair<std::string_view, sbg::MotionProfile>, 13> table{{
    {"general_purpose", GeneralPurpose},
    {"automotive", Automotive},
    {"marine", Marine},
    {"airplane", Airplane},
    {"helicopter", Helicopter},
    {"pedestrian", Pedestrian},
    {"uav_rotary_wing", UavRotaryWing},
    {"heavy_machinery", HeavyMachinery},
    {"static", Static},
    {"truck", Truck},
    {"railway", Railway},
    {"off_road_vehicle", OffRoadVehicle},
    {"underwater", Underwater},
  }};
  for (const auto & [name, value] : table) {
    if (name == s) {
      return value;
    }
  }
  return GeneralPurpose;
}

sbg::PortAssignment port_from_string(std::string_view s)
{
  using enum sbg::PortAssignment;
  constexpr std::array<std::pair<std::string_view, sbg::PortAssignment>, 7> table{{
    {"port_a", PortA},
    {"port_b", PortB},
    {"port_c", PortC},
    {"port_d", PortD},
    {"port_e", PortE},
    {"internal", Internal},
    {"disabled", Disabled},
  }};
  for (const auto & [name, value] : table) {
    if (name == s) {
      return value;
    }
  }
  return Disabled;
}

sbg::AxisDirection axis_from_string(std::string_view s)
{
  using enum sbg::AxisDirection;
  constexpr std::array<std::pair<std::string_view, sbg::AxisDirection>, 6> table{{
    {"forward", Forward},
    {"backward", Backward},
    {"left", Left},
    {"right", Right},
    {"up", Up},
    {"down", Down},
  }};
  for (const auto & [name, value] : table) {
    if (name == s) {
      return value;
    }
  }
  return Forward;
}

sbg::MagModel mag_model_from_string(std::string_view s)
{
  return s == "external_ecom" ? sbg::MagModel::ExternalEcom : sbg::MagModel::InternalNormal;
}

sbg::GnssInstallationMode gnss_mode_from_string(std::string_view s)
{
  using enum sbg::GnssInstallationMode;
  constexpr std::array<std::pair<std::string_view, sbg::GnssInstallationMode>, 4> table{{
    {"single", Single},
    {"dual_auto", DualAuto},
    {"dual_rough", DualRough},
    {"dual_precise", DualPrecise},
  }};
  for (const auto & [name, value] : table) {
    if (name == s) {
      return value;
    }
  }
  return Single;
}

// gpl fixed_size<>:[3] guarantees the vector is length 3.
std::array<float, 3> to_lever_arm(const std::vector<double> & v)
{
  return {static_cast<float>(v[0]), static_cast<float>(v[1]), static_cast<float>(v[2])};
}

}  // namespace

// pImpl-ish holder so generate_parameter_library's generated types stay out
// of the public header. The generated header places `ParamListener` and
// `Params` into the `sbg_driver` namespace (the top-level YAML key), so
// unqualified `ParamListener` here resolves to the generated type.
class SbgDriverNode::ParamHolder
{
public:
  explicit ParamHolder(rclcpp_lifecycle::LifecycleNode * node)
  : listener(node->get_node_parameters_interface())
  {
  }

  ParamListener listener;
};

SbgDriverNode::SbgDriverNode(const rclcpp::NodeOptions & options)
: rclcpp_lifecycle::LifecycleNode(
    "sbg_driver", rclcpp::NodeOptions(options).use_intra_process_comms(true))
{
  // Parameters declared lazily in on_configure so we don't pay the cost
  // until the lifecycle requests it.
}

SbgDriverNode::~SbgDriverNode() = default;

sbg::TransportConfig SbgDriverNode::build_transport_config() const
{
  const auto params = params_->listener.get_params();
  const auto & t = params.transport;

  if (t.type == "file") {
    return sbg::transport::FileReplay{
      .path = t.file.path,
      .real_time_pace = t.file.real_time_pace,
    };
  } else if (t.type == "serial") {
    return sbg::transport::Serial{
      .port = t.serial.port,
      .baud = static_cast<std::uint32_t>(t.serial.baud),
    };
  } else if (t.type == "udp") {
    return sbg::transport::Udp{
      .remote_ip = t.udp.remote_ip,
      .in_port = static_cast<std::uint16_t>(t.udp.in_port),
      .out_port = static_cast<std::uint16_t>(t.udp.out_port),
    };
  }
  // generate_parameter_library's `one_of<>` validation guarantees we
  // never reach here, but the compiler doesn't know that.
  throw std::runtime_error("unreachable: unknown transport type '" + t.type + "'");
}

SbgDriverNode::CallbackReturn SbgDriverNode::on_configure(const rclcpp_lifecycle::State &)
{
  RCLCPP_INFO(get_logger(), "configuring");
  try {
    params_ = std::make_unique<ParamHolder>(this);
  } catch (const std::exception & e) {
    RCLCPP_ERROR(get_logger(), "parameter listener failed: %s", e.what());
    return CallbackReturn::FAILURE;
  }

  const auto params = params_->listener.get_params();
  Publishers::Config pub_cfg{
    .imu_data_topic = params.topics.imu_data,
    .imu_temperature_topic = params.topics.imu_temperature,
    .mag_topic = params.topics.mag,
    .nav_sat_fix_topic = params.topics.nav_sat_fix,
    .time_reference_topic = params.topics.time_reference,
    .odom_topic = params.topics.odom,
    .ekf_nav_sat_fix_topic = params.topics.ekf_nav_sat_fix,
    .nmea_topic = params.topics.nmea,
    .sbg_status_topic = params.topics.sbg_status,
    .sbg_ekf_status_topic = params.topics.sbg_ekf_status,
    .sbg_air_data_status_topic = params.topics.sbg_air_data_status,
    .sbg_event_topic = params.topics.sbg_event,
    .sbg_gps_raw_topic = params.topics.sbg_gps_raw,
    .sbg_mag_calib_topic = params.topics.sbg_mag_calib,
    .sbg_ship_motion_topic = params.topics.sbg_ship_motion,
    .imu_frame_id = params.frames.imu,
    .gps_frame_id = params.frames.gps,
    .time_reference_frame_id = params.frames.time_reference,
    .odom_frame_id = params.frames.odom,
    .base_frame_id = params.frames.base,
    .broadcast_odom_to_base = params.tf.broadcast_odom_to_base,
    .publish_ekf_nav_sat_fix = params.outputs.publish_ekf_nav_sat_fix,
    .publish_nmea_gga = params.outputs.publish_nmea_gga,
    .convention = params.convention.use_enu ? FrameConvention::Enu : FrameConvention::Ned,
    .imu_covariance = resolve_imu_covariance(
      params.imu.sensor_model, params.imu.accel_noise_stddev, params.imu.gyro_noise_stddev),
  };
  publishers_ = std::make_unique<Publishers>(*this, std::move(pub_cfg));

  // ---- diagnostic_updater ------------------------------------------------
  // Read-only snapshots from publishers_->diag_snapshot() drive each task.
  // Updater publishes on its own timer (default 1 Hz).
  diagnostics_ = std::make_unique<diagnostic_updater::Updater>(
    get_node_base_interface(), get_node_clock_interface(), get_node_logging_interface(),
    get_node_parameters_interface(), get_node_timers_interface(), get_node_topics_interface());
  diagnostics_->setHardwareID("sbg_systems_ins");

  diagnostics_->add("Device", [this](diagnostic_updater::DiagnosticStatusWrapper & stat) {
    const auto snap = publishers_->diag_snapshot();
    if (snap.last_log_stamp_ns == 0) {
      stat.summary(diagnostic_msgs::msg::DiagnosticStatus::WARN, "No logs received yet");
      return;
    }
    const auto now_ns = get_clock()->now().nanoseconds();
    const auto age_s = static_cast<double>(now_ns - snap.last_log_stamp_ns) / 1e9;
    stat.add("seconds_since_last_log", age_s);
    stat.add("device_status_general", snap.last_device_status_general);
    if (age_s > 2.0) {
      stat.summary(diagnostic_msgs::msg::DiagnosticStatus::ERROR, "Stale device — no recent logs");
    } else if (!snap.has_device_status) {
      stat.summary(
        diagnostic_msgs::msg::DiagnosticStatus::WARN,
        "Receiving data but no SBG_ECOM_LOG_STATUS yet");
    } else {
      stat.summary(diagnostic_msgs::msg::DiagnosticStatus::OK, "Streaming");
    }
  });

  diagnostics_->add("EKF Solution", [this](diagnostic_updater::DiagnosticStatusWrapper & stat) {
    const auto snap = publishers_->diag_snapshot();
    if (!snap.has_ekf_status) {
      stat.summary(diagnostic_msgs::msg::DiagnosticStatus::WARN, "Waiting for first EKF Nav log");
      return;
    }
    stat.add("solution_mode", static_cast<int>(snap.last_ekf_solution_mode));
    stat.addf("raw_status", "0x%08x", snap.last_ekf_status_raw);
    // Solution mode: 0 uninitialized, 1 vertical gyro, 2 AHRS, 3 nav-velocity,
    // 4 nav-position. <3 is degraded; ==4 is full INS.
    if (snap.last_ekf_solution_mode >= 4) {
      stat.summary(diagnostic_msgs::msg::DiagnosticStatus::OK, "NAV_POSITION");
    } else if (snap.last_ekf_solution_mode >= 3) {
      stat.summary(diagnostic_msgs::msg::DiagnosticStatus::OK, "NAV_VELOCITY");
    } else if (snap.last_ekf_solution_mode == 2) {
      stat.summary(diagnostic_msgs::msg::DiagnosticStatus::WARN, "AHRS only (no nav)");
    } else if (snap.last_ekf_solution_mode == 1) {
      stat.summary(diagnostic_msgs::msg::DiagnosticStatus::WARN, "Vertical gyro");
    } else {
      stat.summary(diagnostic_msgs::msg::DiagnosticStatus::ERROR, "Uninitialized");
    }
  });

  diagnostics_->add("IMU Temperature", [this](diagnostic_updater::DiagnosticStatusWrapper & stat) {
    const auto snap = publishers_->diag_snapshot();
    if (!snap.has_imu_temperature) {
      stat.summary(diagnostic_msgs::msg::DiagnosticStatus::WARN, "No IMU data yet");
      return;
    }
    const double t = static_cast<double>(snap.last_imu_temperature_c);
    stat.add("temperature_c", t);
    if (t < -40.0 || t > 85.0) {
      stat.summary(diagnostic_msgs::msg::DiagnosticStatus::ERROR, "Out of typical operating range");
    } else if (t > 70.0) {
      stat.summary(
        diagnostic_msgs::msg::DiagnosticStatus::WARN, "Approaching upper operating limit");
    } else {
      stat.summary(diagnostic_msgs::msg::DiagnosticStatus::OK, "Nominal");
    }
  });

  // ---- /rtcm subscription -------------------------------------------------
  rtcm_sub_ = create_subscription<rtcm_msgs::msg::Message>(
    "rtcm", rclcpp::QoS(20).reliable(), [this](std::shared_ptr<const rtcm_msgs::msg::Message> msg) {
      if (!device_ || msg->message.empty()) {
        return;
      }
      auto bytes = std::as_bytes(std::span<const std::uint8_t>(msg->message));
      auto result = device_->write_rtcm(bytes);
      if (!result) {
        RCLCPP_WARN_THROTTLE(
          get_logger(), *get_clock(), 5000, "RTCM write failed: %s",
          sbg::to_string(result.error()).data());
      }
    });

  // ---- mag-calibration services ------------------------------------------
  // Each callback pauses the I/O thread (sbgECom command/response would
  // otherwise race with the polling read), runs the Configurator command,
  // and restarts the I/O thread. Services only function in ACTIVE state.
  start_mag_cal_srv_ = create_service<std_srvs::srv::Trigger>(
    "sbg/start_mag_calibration", [this](
                                   const std::shared_ptr<std_srvs::srv::Trigger::Request> /*req*/,
                                   std::shared_ptr<std_srvs::srv::Trigger::Response> res) {
      if (!device_) {
        res->success = false;
        res->message = "node not activated";
        return;
      }
      if (io_thread_.joinable()) {
        io_thread_.request_stop();
        io_thread_.join();
      }
      auto r = device_->configurator().start_mag_calibration(sbg::MagCalibMode::ThreeD);
      // Always restart the I/O thread regardless of command outcome.
      io_thread_ = std::jthread{
        [this](std::stop_token st) { device_->run(st, std::chrono::milliseconds{4}); }};
      res->success = r.has_value();
      res->message = r ? "calibration started; move sensor through full 3D range, then call save"
                       : std::string{sbg::to_string(r.error())};
    });
  save_mag_cal_srv_ = create_service<std_srvs::srv::Trigger>(
    "sbg/save_mag_calibration", [this](
                                  const std::shared_ptr<std_srvs::srv::Trigger::Request> /*req*/,
                                  std::shared_ptr<std_srvs::srv::Trigger::Response> res) {
      if (!device_) {
        res->success = false;
        res->message = "node not activated";
        return;
      }
      if (io_thread_.joinable()) {
        io_thread_.request_stop();
        io_thread_.join();
      }
      auto restart_io_thread = [this]() {
        io_thread_ = std::jthread{
          [this](std::stop_token st) { device_->run(st, std::chrono::milliseconds{4}); }};
      };
      auto cfg = device_->configurator();
      if (auto r = cfg.compute_mag_calibration(); !r) {
        restart_io_thread();
        res->success = false;
        res->message = std::format("compute failed: {}", sbg::to_string(r.error()));
        return;
      }
      if (auto r = cfg.save_mag_calibration_results(); !r) {
        restart_io_thread();
        res->success = false;
        res->message = std::format("upload failed: {}", sbg::to_string(r.error()));
        return;
      }
      if (auto r = cfg.save_settings(); !r) {
        restart_io_thread();
        res->success = false;
        res->message = std::format("save_settings failed: {}", sbg::to_string(r.error()));
        return;
      }
      // Device reboots after save_settings - drop the link rather than spin
      // up a thread that will fail on a closed handle. Resetting device_ also
      // makes a subsequent start/save service call short-circuit on the
      // `!device_` guard instead of spawning an I/O thread on a dead handle.
      // The user re-cycles the lifecycle (deactivate -> activate) to reconnect.
      device_.reset();
      res->success = true;
      res->message =
        "calibration uploaded and persisted; device will reboot. Re-cycle the lifecycle "
        "(deactivate then activate) to reconnect.";
    });

  RCLCPP_INFO(
    get_logger(), "configured: transport=%s, frame=%s, convention=%s",
    params.transport.type.c_str(), params.frames.imu.c_str(),
    params.convention.use_enu ? "ENU" : "NED");
  return CallbackReturn::SUCCESS;
}

SbgDriverNode::CallbackReturn SbgDriverNode::apply_device_configuration()
{
  const auto params = params_->listener.get_params();
  const auto & cd = params.configure_device;
  if (!cd.enable) {
    return CallbackReturn::SUCCESS;
  }
  RCLCPP_INFO(
    get_logger(), "configure_device.enable=true: provisioning device from params (RAM only)");

  auto cfg = device_->configurator();
  // Log + return success/failure of one step; used for fail-fast below.
  const auto run = [this](const char * what, const sbg::Result<void> & r) {
    if (r) {
      RCLCPP_INFO(get_logger(), "configure_device: applied %s", what);
    } else {
      RCLCPP_ERROR(
        get_logger(), "configure_device: %s failed: %s", what, sbg::to_string(r.error()).data());
    }
    return static_cast<bool>(r);
  };

  if (cd.motion_profile.apply) {
    if (!run(
          "motion_profile",
          cfg.set_motion_profile(motion_profile_from_string(cd.motion_profile.value)))) {
      return CallbackReturn::FAILURE;
    }
  }

  if (cd.aiding.apply) {
    const sbg::AidingAssignment assignment{
      .gps1_port = port_from_string(cd.aiding.gps1_port),
      .rtcm_port = port_from_string(cd.aiding.rtcm_port),
      .dvl_port = port_from_string(cd.aiding.dvl_port),
      .air_data_port = port_from_string(cd.aiding.air_data_port),
    };
    if (!run("aiding_assignment", cfg.set_aiding_assignment(assignment))) {
      return CallbackReturn::FAILURE;
    }
  }

  if (cd.imu_alignment.apply) {
    constexpr double k_deg_to_rad = 3.14159265358979323846 / 180.0;
    const auto & ia = cd.imu_alignment;
    const sbg::ImuAlignment alignment{
      .axis_x = axis_from_string(ia.axis_x),
      .axis_y = axis_from_string(ia.axis_y),
      .mis_roll = static_cast<float>(ia.mis_roll_deg * k_deg_to_rad),
      .mis_pitch = static_cast<float>(ia.mis_pitch_deg * k_deg_to_rad),
      .mis_yaw = static_cast<float>(ia.mis_yaw_deg * k_deg_to_rad),
      .lever_arm = to_lever_arm(ia.lever_arm),
    };
    if (!run("imu_alignment", cfg.set_imu_alignment(alignment))) {
      return CallbackReturn::FAILURE;
    }
  }

  if (cd.gnss.apply) {
    const sbg::GnssInstallation installation{
      .lever_arm_primary = to_lever_arm(cd.gnss.lever_arm_primary),
      .lever_arm_secondary = to_lever_arm(cd.gnss.lever_arm_secondary),
      .secondary_mode = gnss_mode_from_string(cd.gnss.secondary_mode),
    };
    if (!run("gnss_installation", cfg.set_gnss_installation(installation))) {
      return CallbackReturn::FAILURE;
    }
  }

  if (cd.mag_model.apply) {
    if (!run("mag_model", cfg.set_magnetometer_model(mag_model_from_string(cd.mag_model.value)))) {
      return CallbackReturn::FAILURE;
    }
  }

  RCLCPP_INFO(
    get_logger(), "configure_device: provisioning complete (call save_settings to persist)");
  return CallbackReturn::SUCCESS;
}

SbgDriverNode::CallbackReturn SbgDriverNode::on_activate(const rclcpp_lifecycle::State &)
{
  RCLCPP_INFO(get_logger(), "activating");

  auto cfg = build_transport_config();
  auto dev_result = sbg::Device::open(std::move(cfg));
  if (!dev_result) {
    RCLCPP_ERROR(get_logger(), "device open failed: %s", sbg::to_string(dev_result.error()).data());
    return CallbackReturn::FAILURE;
  }
  device_.emplace(std::move(*dev_result));

  // Optionally provision the device from configure_device.* params. The I/O
  // thread isn't running yet, so Configurator commands are permitted. On any
  // requested-command failure, abort activation and drop the open handle.
  if (apply_device_configuration() != CallbackReturn::SUCCESS) {
    device_.reset();
    return CallbackReturn::FAILURE;
  }

  device_->set_log_callback([this](const sbg::LogView & v) { publishers_->on_log(v); });

  publishers_->activate();

  io_thread_ =
    std::jthread{[this](std::stop_token st) { device_->run(st, std::chrono::milliseconds{4}); }};

  return CallbackReturn::SUCCESS;
}

SbgDriverNode::CallbackReturn SbgDriverNode::on_deactivate(const rclcpp_lifecycle::State &)
{
  RCLCPP_INFO(get_logger(), "deactivating");
  if (io_thread_.joinable()) {
    io_thread_.request_stop();
    io_thread_.join();
  }
  if (publishers_) {
    publishers_->deactivate();
  }
  device_.reset();
  return CallbackReturn::SUCCESS;
}

SbgDriverNode::CallbackReturn SbgDriverNode::on_cleanup(const rclcpp_lifecycle::State &)
{
  RCLCPP_INFO(get_logger(), "cleaning up");
  rtcm_sub_.reset();
  start_mag_cal_srv_.reset();
  save_mag_cal_srv_.reset();
  diagnostics_.reset();
  publishers_.reset();
  params_.reset();
  return CallbackReturn::SUCCESS;
}

SbgDriverNode::CallbackReturn SbgDriverNode::on_shutdown(const rclcpp_lifecycle::State & state)
{
  RCLCPP_INFO(get_logger(), "shutting down");
  (void)on_deactivate(state);
  (void)on_cleanup(state);
  return CallbackReturn::SUCCESS;
}

SbgDriverNode::CallbackReturn SbgDriverNode::on_error(const rclcpp_lifecycle::State & state)
{
  RCLCPP_ERROR(get_logger(), "lifecycle error transition");
  (void)on_deactivate(state);
  (void)on_cleanup(state);
  return CallbackReturn::SUCCESS;
}

}  // namespace sbg_driver

RCLCPP_COMPONENTS_REGISTER_NODE(sbg_driver::SbgDriverNode)
