// Copyright 2026 sbg_driver maintainers
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#include "sbg_driver/driver_node.hpp"

#include <chrono>
#include <rclcpp_components/register_node_macro.hpp>
#include <utility>

// Generated by generate_parameter_library from params/sbg_driver_params.yaml.
// Lives under build/sbg_driver/include/sbg_driver/ at build time.
#include "sbg_driver/sbg_driver_params.hpp"

namespace sbg_driver
{

// pImpl-ish holder so generate_parameter_library's generated types stay out
// of the public header. The generated header places `ParamListener` and
// `Params` into the `sbg_driver` namespace (the top-level YAML key), so
// unqualified `ParamListener` here resolves to the generated type.
class SbgDriverNode::ParamHolder
{
public:
  explicit ParamHolder(rclcpp_lifecycle::LifecycleNode * node)
  : listener(node->get_node_parameters_interface())
  {
  }

  ParamListener listener;
};

SbgDriverNode::SbgDriverNode(const rclcpp::NodeOptions & options)
: rclcpp_lifecycle::LifecycleNode(
    "sbg_driver", rclcpp::NodeOptions(options).use_intra_process_comms(true))
{
  // Parameters declared lazily in on_configure so we don't pay the cost
  // until the lifecycle requests it.
}

SbgDriverNode::~SbgDriverNode() = default;

sbg::TransportConfig SbgDriverNode::build_transport_config() const
{
  const auto params = params_->listener.get_params();
  const auto & t = params.transport;

  if (t.type == "file") {
    return sbg::transport::FileReplay{
      .path = t.file.path,
      .real_time_pace = t.file.real_time_pace,
    };
  } else if (t.type == "serial") {
    return sbg::transport::Serial{
      .port = t.serial.port,
      .baud = static_cast<std::uint32_t>(t.serial.baud),
    };
  } else if (t.type == "udp") {
    return sbg::transport::Udp{
      .remote_ip = t.udp.remote_ip,
      .in_port = static_cast<std::uint16_t>(t.udp.in_port),
      .out_port = static_cast<std::uint16_t>(t.udp.out_port),
    };
  }
  // generate_parameter_library's `one_of<>` validation guarantees we
  // never reach here, but the compiler doesn't know that.
  throw std::runtime_error("unreachable: unknown transport type '" + t.type + "'");
}

SbgDriverNode::CallbackReturn SbgDriverNode::on_configure(const rclcpp_lifecycle::State &)
{
  RCLCPP_INFO(get_logger(), "configuring");
  try {
    params_ = std::make_unique<ParamHolder>(this);
  } catch (const std::exception & e) {
    RCLCPP_ERROR(get_logger(), "parameter listener failed: %s", e.what());
    return CallbackReturn::FAILURE;
  }

  const auto params = params_->listener.get_params();
  Publishers::Config pub_cfg{
    .imu_data_topic = params.topics.imu_data,
    .imu_temperature_topic = params.topics.imu_temperature,
    .mag_topic = params.topics.mag,
    .nav_sat_fix_topic = params.topics.nav_sat_fix,
    .time_reference_topic = params.topics.time_reference,
    .odom_topic = params.topics.odom,
    .imu_frame_id = params.frames.imu,
    .gps_frame_id = params.frames.gps,
    .time_reference_frame_id = params.frames.time_reference,
    .odom_frame_id = params.frames.odom,
    .base_frame_id = params.frames.base,
    .broadcast_odom_to_base = params.tf.broadcast_odom_to_base,
    .convention = params.convention.use_enu ? FrameConvention::Enu : FrameConvention::Ned,
  };
  publishers_ = std::make_unique<Publishers>(*this, std::move(pub_cfg));

  RCLCPP_INFO(
    get_logger(), "configured: transport=%s, frame=%s, convention=%s",
    params.transport.type.c_str(), params.frames.imu.c_str(),
    params.convention.use_enu ? "ENU" : "NED");
  return CallbackReturn::SUCCESS;
}

SbgDriverNode::CallbackReturn SbgDriverNode::on_activate(const rclcpp_lifecycle::State &)
{
  RCLCPP_INFO(get_logger(), "activating");

  auto cfg = build_transport_config();
  auto dev_result = sbg::Device::open(std::move(cfg));
  if (!dev_result) {
    RCLCPP_ERROR(get_logger(), "device open failed: %s", sbg::to_string(dev_result.error()).data());
    return CallbackReturn::FAILURE;
  }
  device_.emplace(std::move(*dev_result));

  device_->set_log_callback([this](const sbg::LogView & v) { publishers_->on_log(v); });

  publishers_->activate();

  io_thread_ =
    std::jthread{[this](std::stop_token st) { device_->run(st, std::chrono::milliseconds{4}); }};

  return CallbackReturn::SUCCESS;
}

SbgDriverNode::CallbackReturn SbgDriverNode::on_deactivate(const rclcpp_lifecycle::State &)
{
  RCLCPP_INFO(get_logger(), "deactivating");
  if (io_thread_.joinable()) {
    io_thread_.request_stop();
    io_thread_.join();
  }
  if (publishers_) {
    publishers_->deactivate();
  }
  device_.reset();
  return CallbackReturn::SUCCESS;
}

SbgDriverNode::CallbackReturn SbgDriverNode::on_cleanup(const rclcpp_lifecycle::State &)
{
  RCLCPP_INFO(get_logger(), "cleaning up");
  publishers_.reset();
  params_.reset();
  return CallbackReturn::SUCCESS;
}

SbgDriverNode::CallbackReturn SbgDriverNode::on_shutdown(const rclcpp_lifecycle::State & state)
{
  RCLCPP_INFO(get_logger(), "shutting down");
  (void)on_deactivate(state);
  (void)on_cleanup(state);
  return CallbackReturn::SUCCESS;
}

SbgDriverNode::CallbackReturn SbgDriverNode::on_error(const rclcpp_lifecycle::State & state)
{
  RCLCPP_ERROR(get_logger(), "lifecycle error transition");
  (void)on_deactivate(state);
  (void)on_cleanup(state);
  return CallbackReturn::SUCCESS;
}

}  // namespace sbg_driver

RCLCPP_COMPONENTS_REGISTER_NODE(sbg_driver::SbgDriverNode)
